version: 0.2

phases:
  #Specifying that we will need JDK 8 for this application
  install:
    runtime-version:
      - java: corretto8
  
  build:
    commands:
      - java -version
      - mvn clean package
  
artifacts:
  files:
    - Dockerfile
    - target/rest.war