version: 0.2

phases:
  #Installing JDK for our aws server
  install:
    commands:
      - apt-get install openjdk-8-JDK
    
  pre-build:
    commands:
      - touch database.properties
      - echo 'url='
  
  build:
    commands:
      - mvn clean package
  
  artifacts:
    files:
      - Dockerfile
      - src\main\resources\database.properties