version: 0.2

phases:
  #Specifying that we will need JDK 8 for this application
  # install:
  #   runtime-versions:
  #     java: corretto8
  
  build:
    commands:
      - echo "Building .tar file"
      - java -version
      - echo ${url}
      - mvn clean package
  
  post_build:
    commands:
      - echo "Testing and sending sonar cloud report"
      - mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
  
artifacts:
  files:
    - Dockerfile
    - target/**/*