version: 0.2

phases:
  #Specifying that we will need JDK 8 for this application
  install:
    runtime-versions:
      java: corretto8
  
  build:
    commands:
      - java -version
      - echo ${url}
      - mvn clean package
  
artifacts:
  files:
    - Dockerfile
    - target/**/*